### ISSUE TITLE
Roadmap and vision of project

### ISSUE THREAD

**Issue by betofloresbaca** [SharpEngine/SharpEngine.Core#7]
It would be nice to have the roadmap about the future of the development of this engine and the vision of what it should be

I have found that the experience programming components in this engine is pretty similar to how the components are programmed in Unity due to the language and the architecture. Is the purpose for this engine to have a coding experience near Unity codding?

I think the project can use the Github issues board to list pending to implement features or bug fixes so more people (including me) can know what needs to be done and choose items for development avoiding to do re-work.

**Comment by AlexisHuvier** [comment]
Its a good idea.
I should take Time for this mater, maybe in a few days.

For now, SharpEngine is only for 2d and a little project made originally for me.
Its architecture is pretty similar yes. I liké this system.
The first goal is to create a complete 2d engine, with some packages and an optional editor
